package com.banking.transactionservice.domain.model;

/**
 * PIX key types defined by the Brazilian Central Bank.
 *
 * Each type has specific validation rules:
 * - CPF: 11 numeric digits
 * - CNPJ: 14 numeric digits
 * - EMAIL: RFC 5322 format
 * - PHONE: E.164 format (+55 11 99999-9999)
 * - RANDOM: UUID v4 generated by the system
 */
public enum PixKeyType {
  CPF,
  CNPJ,
  EMAIL,
  PHONE,
  RANDOM
}
